[project]
name = "playbook-workstation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.2.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=26.1.0",
]
